Ureca-Mini-Project-Team4/Oh-no-its-me

springboot-app/src/main/java/com/uplus/eureka/vote/contoller/VoteController.java, springboot-app/src/main/java/com/uplus/eureka/vote/model/dao/VoteDao.java, springboot-app/src/main/java/com/uplus/eureka/vote/model/dto/Vote.java, springboot-app/src/main/java/com/uplus/eureka/vote/model/dto/VoteException.java, springboot-app/src/main/java/com/uplus/eureka/vote/model/dto/VoteRequset.java, springboot-app/src/main/java/com/uplus/eureka/vote/model/dto/VoteResult.java, springboot-app/src/main/java/com/uplus/eureka/vote/model/service/VoteService.java, springboot-app/src/main/java/com/uplus/eureka/vote/model/service/VoteServiceImp.java, springboot-app/src/main/resources/application.properties, springboot-app/src/main/resources/mapper/vote.xml
#11 
Vote의 특정 투표 결과 조회 부분 구현하였습니다.
results부분에 1등의 이름과 투표수 저장합니다.
=> FEAT: #11 Vote API 특정 투표 결과 조회

.gitignore, springboot-app/src/main/java/com/uplus/eureka/user/controller/UserController.java, springboot-app/src/main/java/com/uplus/eureka/user/model/dao/UserDao.java, springboot-app/src/main/java/com/uplus/eureka/user/model/dto/LoginRequest.java, springboot-app/src/main/java/com/uplus/eureka/user/model/dto/User.java, springboot-app/src/main/java/com/uplus/eureka/user/model/service/UserService.java, springboot-app/src/main/java/com/uplus/eureka/user/model/service/UserServiceImp.java, springboot-app/src/main/resources/mapper/users.xml
#3 
- **로그인✅**
- api/user/login
- **정보 확인✅**
-  api/user/{`userId`}
- **비밀번호 변경✅**
=> FEAT: #3 User API 로그인 및 정보 확인

springboot-app/src/main/java/com/uplus/eureka/candidate/controller/CandidateController.java, springboot-app/src/main/java/com/uplus/eureka/candidate/model/dto/CandidateNotFoundException.java, springboot-app/src/main/java/com/uplus/eureka/poll/controller/PollController.java, springboot-app/src/main/java/com/uplus/eureka/poll/model/dto/PollServiceException.java, springboot-app/src/main/java/com/uplus/eureka/vote/contoller/VoteController.java
#24 
try - catch문 추가해서 에러 처리 했습니다
=> FEAT: #24 add Exception for Poll and Candidate API

springboot-app/src/main/java/com/uplus/eureka/vote/contoller/VoteController.java, springboot-app/src/main/java/com/uplus/eureka/vote/model/dao/VoteDao.java, springboot-app/src/main/java/com/uplus/eureka/vote/model/dto/VoteResult.java, springboot-app/src/main/java/com/uplus/eureka/vote/model/service/VoteService.java, springboot-app/src/main/java/com/uplus/eureka/vote/model/service/VoteServiceImp.java, springboot-app/src/main/resources/mapper/vote.xml
> #27
투표 완료시에 is_voted를 true로 바꾸는 api 구현
=> FEAT: #27 투표 완료 등록 api

springboot-app/src/main/java/com/uplus/eureka/vote/contoller/VoteController.java, springboot-app/src/main/java/com/uplus/eureka/vote/model/dao/VoteDao.java, springboot-app/src/main/java/com/uplus/eureka/vote/model/dto/VoteRequest.java, springboot-app/src/main/java/com/uplus/eureka/vote/model/service/VoteService.java, springboot-app/src/main/java/com/uplus/eureka/vote/model/service/VoteServiceImp.java
> ex) #34, #34
> vote swagger 문서화
=> FEAT: #34 vote swagger 문서화

springboot-app/src/main/java/com/uplus/eureka/comment/model/dto/Comment.java
중복 JsonProperties annotation 충돌 해결
=> BUG: Comment - JsonProperties annotation 중복 충동

.github/workflows/backend-cicd.yml, README.md, springboot-app/Dockerrun.aws.json, springboot-app/dockerfile, springboot-app/src/main/resources/application.properties
> #66
- 백엔드 자동 배포를 위한 도커파일 작성 (main 브랜치 Push 시 트리거)
- 도커 허브 레포지토리에 업로드 및 aws 환경변수 설정
=> DEPLOY: #66 Docker + Github Action CI/CD 

react-app/src/components/InputField/InputField.tsx, react-app/src/components/InputField/InputField.types.ts
> Close #81
- 타입 인터페이스 정의
- 컴포넌트 구현
=> FEAT: #81 InputField 컴포넌트 구현

react-app/src/components/Button/Button.tsx, react-app/src/components/Button/Button.types.ts
> Close #80
> 버튼 컴포넌트를 만들었습니다.
=> FEAT: #80 버튼 컴포넌트 만들기

react-app/src/components/Comment/Comment.tsx, react-app/src/components/Profile/Profile.tsx
=> FEAT: #93 Profile Comment 제작

springboot-app/src/main/java/com/uplus/eureka/candidate/controller/CandidateController.java, springboot-app/src/main/java/com/uplus/eureka/candidate/model/dao/CandidateDao.java, springboot-app/src/main/java/com/uplus/eureka/candidate/model/dto/Candidate.java, springboot-app/src/main/java/com/uplus/eureka/candidate/model/service/CandidateService.java, springboot-app/src/main/resources/mapper/candidates.xml
#104 
기존에 return으로 값을 배출하지 않던 상황을 userName과 questionText를 포함하여 보내도록 수정
=> [REFACT] #104 candidate(백엔드) 수정

springboot-app/src/main/java/com/uplus/eureka/candidate/model/dao/CandidateDao.java, springboot-app/src/main/resources/mapper/candidates.xml
=> FEAT: Candidate 백엔드 수정

react-app/src/components/Comment/Comment.tsx, react-app/src/components/Comment/Dropdown.tsx, react-app/src/components/Winner/Winner.tsx
=> FEAT: #108 Comment 수정 및 import react 제거

react-app/src/apis/candidate/postCandidate.ts
=> FEAT: #115 Candidate API 모듈화

springboot-app/src/main/java/com/uplus/eureka/vote/model/dao/VoteDao.java, springboot-app/src/main/java/com/uplus/eureka/vote/model/dto/VoteResult.java, springboot-app/src/main/java/com/uplus/eureka/vote/model/service/VoteServiceImp.java, springboot-app/src/main/resources/mapper/vote.xml
=> FEAT: #135 vote에서 icon 받아올 수 있도록 수정

react-app/src/apis/axiosInstance.ts, react-app/src/apis/poll/getPoll.ts, react-app/src/hook/useAuth.ts, react-app/src/pages/ChangePW.tsx, react-app/src/pages/Login.tsx, react-app/src/pages/Main.tsx
=> FEAT: #139 타이머 구현

react-app/src/apis/axiosInstance.ts, react-app/src/hook/useAuth.ts, react-app/src/pages/ChangePW.tsx
=> FEAT: #142 로그인 예외 처리 수정

springboot-app/src/main/java/com/uplus/eureka/poll/controller/PollController.java, springboot-app/src/main/java/com/uplus/eureka/poll/model/dao/PollDao.java, springboot-app/src/main/java/com/uplus/eureka/poll/model/service/PollService.java, springboot-app/src/main/java/com/uplus/eureka/poll/model/service/PollServiceImp.java, springboot-app/src/main/resources/mapper/poll.xml
#144
가장 최근의 pollId를 4개 가져오는 쿼리문
=> FEAT: #144 poll-latest 추가

springboot-app/src/main/java/com/uplus/eureka/SpringBootTestApplication.java, springboot-app/src/main/java/com/uplus/eureka/candidate/controller/CandidateController.java, springboot-app/src/main/java/com/uplus/eureka/candidate/model/dao/CandidateDao.java, springboot-app/src/main/java/com/uplus/eureka/candidate/model/dto/Candidate.java, springboot-app/src/main/java/com/uplus/eureka/candidate/model/service/CandidateService.java, springboot-app/src/main/java/com/uplus/eureka/candidate/scheduler/CandidateScheduler.java, springboot-app/src/main/java/com/uplus/eureka/poll/scheduler/PollScheduler.java, springboot-app/src/main/resources/mapper/candidates.xml
#147
자동으로 14시에 poll candidate 호출하도록 변경
=> FEAT: #147 candidate 및 poll 수정

springboot-app/src/main/java/com/uplus/eureka/candidate/model/dto/Candidate.java, springboot-app/src/main/java/com/uplus/eureka/candidate/model/service/CandidateService.java, springboot-app/src/main/java/com/uplus/eureka/candidate/scheduler/CandidateScheduler.java, springboot-app/src/main/java/com/uplus/eureka/poll/scheduler/PollScheduler.java, springboot-app/src/main/resources/mapper/candidates.xml
=> FEAT: #147 poll candidate api 수정

react-app/src/apis/candidate/getCandidateLatest.ts, react-app/src/components/Candidate/Candidate.tsx, react-app/src/components/Candidate/Candidate.types.ts, react-app/src/components/Candidate/CandidateGroup.tsx
=> FEAT: #152 Feature/candidate group

react-app/src/pages/Main.tsx, springboot-app/src/main/java/com/uplus/eureka/candidate/scheduler/CandidateScheduler.java, springboot-app/src/main/java/com/uplus/eureka/poll/scheduler/PollScheduler.java
Close #160
타이머 시간이 0 보다 작아지면 더 이상 restTime이 변경되지 않도록 수정 및 결과 확인으로 버튼 변경
=> FEAT: #160 Feature/main page 상태에 따른 버튼 상태 부여

react-app/src/pages/Comment.tsx
Close #164 
Comment에서 타입 에러로 빌드 실패 에러 해결
=> FIX: #164 Comment - 타입 에러 해결

springboot-app/src/main/java/com/uplus/eureka/candidate/model/dto/Candidate.java
> ex) #171, #171 
candidate dto에 candidateId 추가하기
=> FIX: candidate dto에 candidateId 추가하기

react-app/src/apis/poll/getPoll.ts, react-app/src/components/Comment/Comment.tsx, react-app/src/components/Comment/CommentInputField.tsx, react-app/src/components/WinnerCard/WinnerCard.tsx, react-app/src/pages/Comment.tsx, react-app/src/styles/index.css
Close #168 
결과 확인, 댓글 반응형 CSS 구현
=> FEAT: #168 결과 확인, 댓글 반응형 CSS 구현

springboot-app/src/main/java/com/uplus/eureka/candidate/scheduler/CandidateScheduler.java, springboot-app/src/main/java/com/uplus/eureka/poll/scheduler/PollScheduler.java
#178
scheduled 어노테이션에 zone을 추가하여 한국시간으로 되도록 조정
=> REFACT: #178 한국시간으로 조정

react-app/src/hook/useAuth.ts, react-app/src/pages/Main.tsx, react-app/src/pages/Vote.tsx
> ex) #181, #181 
로컬에 voted를 저장하여 불러올 수 있게 수정하였습니다.
=> FEAT: #181 로컬에 voted 저장하기

springboot-app/src/main/java/com/uplus/eureka/user/controller/UserController.java, springboot-app/src/main/java/com/uplus/eureka/user/model/dto/PasswordUpdateRequest.java, springboot-app/src/main/java/com/uplus/eureka/user/model/service/UserService.java, springboot-app/src/main/java/com/uplus/eureka/user/model/service/UserServiceImp.java, springboot-app/src/main/resources/mapper/users.xml
> Close #189 
> 비밀번호 API 요청 바디에 username 필드 추가
=> REFACTOR: #189 비밀번호 API 요청 바디에 username 필드 추가

react-app/src/pages/ChangePW.tsx, react-app/src/pages/Login.tsx
=> REFACT: #192 사진 경로 변경

react-app/src/components/Comment/Comment.tsx, react-app/src/components/Comment/CommentInputField.tsx, react-app/src/components/Comment/Dropdown.tsx, react-app/src/components/Modal/Modal.tsx, react-app/src/components/Modal/Modal.types.ts, react-app/src/pages/Comment.tsx, react-app/src/pages/Vote.tsx
Close #177 #196 
댓글 수정, 삭제
기능이 정상적으로 작동하는지 봐주세요
=> FEAT: Comment 댓글 수정 삭제

react-app/src/hook/useAuth.ts, react-app/src/pages/ChangePW.tsx, react-app/src/pages/Login.tsx, springboot-app/src/main/java/com/uplus/eureka/util/JwtUtil.java
=> REFACT: #203 로그인, 비밀번호 변경 페이지 REACT QUERY로 변경

react-app/src/pages/Comment.tsx, react-app/src/pages/Result.tsx
Close #175 
Comment CSS 정리 및 Loading 전체 통일
=> FEAT: Comment CSS 정리 및 Loading 전체 통일

react-app/src/components/Candidate/Candidate.tsx, react-app/src/components/Comment/CommentInputField.tsx, react-app/src/components/Loading/Loading.tsx, react-app/src/components/Profile/Profile.tsx, react-app/src/components/Toast/Toast.tsx, react-app/src/components/WinnerCard/WinnerCard.tsx, react-app/src/constants/iconPath.ts, react-app/src/constants/imagePath.ts, react-app/src/pages/ChangePW.tsx, react-app/src/pages/Comment.tsx, react-app/src/pages/Home.tsx, react-app/src/pages/Login.tsx, react-app/src/pages/Result.tsx, react-app/src/pages/Vote.tsx
> Close #211 
> 모든 이미지 경로를 상수화해서 정리해뒀습니다!
=> REFACTOR: #211 모든 이미지 경로 상수 파일로 리팩토링

springboot-app/src/main/java/com/uplus/eureka/config/WebMvcConfiguration.java, springboot-app/src/main/java/com/uplus/eureka/interceptor/JWTInterceptor.java, springboot-app/src/main/java/com/uplus/eureka/user/controller/UserController.java, springboot-app/src/main/java/com/uplus/eureka/util/JwtUtil.java
> Close #209 
- addViewControllers fallbck 설정 추가
- 리프레시 토큰 로직 강화
=> FIX: #209 로그인 404 에러 수정

react-app/src/components/Loading/Loading.tsx, react-app/src/hook/useLogin.ts, react-app/src/pages/Login.tsx
> Close #228 
- 로그인 로딩 추가(`IsPending`)
- 로딩 컴포넌트 너비 풀 -> 원래 사이즈로 수정
=> REFACTOR: #228 로그인 로딩 추가

react-app/src/components/Loading/Loading.tsx, react-app/src/pages/Vote.tsx
> ex) CLOSE #232 
loading 컴포넌트를 수정하였습니다.
=> BUG: #232 Loading 컴포넌트 배경 흰색으로 만들기

react-app/src/components/Candidate/Candidate.tsx, react-app/src/pages/Vote.tsx
=> REFACTOR: #240 vote 페이지 수정

react-app/src/pages/Result.tsx
> Close #236 
> 랭킹 페이지 새로고침 전체 div에 적용, 반응형 일부 수정
=> REFACTOR: #236 랭킹 페이지 새로고침 전체 div에 적용

react-app/src/pages/ChangePW.tsx, react-app/src/pages/Login.tsx, react-app/src/pages/Vote.tsx, react-app/src/routes.tsx, react-app/vercel.json
> ex) CLOSE #247 
> 아이디 대신 이름이라고 수정
비밀번호 변경 폰트 수정
투표 맨 처음 페이지 이전 버튼 시 메인화면으로 수정
배포된 사이트에서 새로고침 시에 404 에러가 뜨는 것을 수정
=> FIX: #247 배포된 사이트 새로고침 문제
